### ISSUE TITLE
It would be nice if the keys you used for counties were FIPS

### ISSUE THREAD

**Issue by openbrian** [digiphilo/covid#2]
https://en.wikipedia.org/wiki/List_of_United_States_FIPS_codes_by_county

This would make it easier to integrated with other data sources like Census.

**Comment by digiphilo** [comment]
Thanks for the suggestion, will get a param added so you can request key as FIPS code.

**Comment by digiphilo** [comment]
you can now use `&fipsKey=true` as a query param for this behavior https://covapi.herokuapp.com/api/total/counties/colorado?fipsKey=true as an example. you can also now use FIPS code in the query request in place of state or county name. if you are only looking for cases or deaths instead of an object with both, use &mode=cases or &mode=deaths. nytimes is reporting some as `Unknown` (or previously `XX999` FIPS), these are filtered out when using FIPS keys.
